SozlukMVC/Controllers/MembersController.cs
using BLL;
using Entity;
using Entity.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System.Web;
using System.Web.Mvc;

namespace SozlukMVC.Controllers
{
    public class MembersController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();
        // GET: Members
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogOff()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult ChangePass()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePass(string oldp, string newp)
        {
            UserStore<Person> store = new UserStore<Person>(_uw.db);

            UserManager<Person> manager = new UserManager<Person>(store);

            string uid = User.Identity.GetUserId();
            Person p = manager.FindById(uid);

            bool isCorrect = manager.CheckPassword(p, oldp);

            if (isCorrect)
            {
                IdentityResult r = manager.ChangePassword(uid, oldp, newp);
                if (r.Succeeded)
                    ViewBag.Success = true;
                else
                    ViewBag.Errors = r.Errors;
            }
            else
                ViewBag.WrongPassword = true;

            return View();
        }



        [HttpGet]
        public ActionResult MyAccount()
        {
            string uid = User.Identity.GetUserId();
            Person person = _uw.db.Users.Find(uid);

            if (person.HasPhoto)
                ViewBag.Photo = "/Uploads/Members/" + uid + ".jpg";

            MyAccountViewModel vm = new MyAccountViewModel();
            vm.Email = person.Email;
            vm.PhoneNumber = person.PhoneNumber;
            return View(vm);
        }
        [HttpPost]
        public ActionResult MyAccount(MyAccountViewModel info, HttpPostedFileBase imgFile)
        {
            UserStore<Person> store = new UserStore<Person>(UnitOfWork.Create());

            UserManager<Person> manager = new UserManager<Person>(store);

            string uid = User.Identity.GetUserId();
            Person person = manager.FindById(uid);

            person.Email = info.Email;
            person.PhoneNumber = info.PhoneNumber;

            if (imgFile != null)
            {
                string path = Server.MapPath("/Uploads/Members/");

                string old = path + person.Id + ".jpg";
                if (System.IO.File.Exists(old))
                    System.IO.File.Delete(old);

                string _new = path + person.Id + ".jpg";
                imgFile.SaveAs(_new);

                person.HasPhoto = true;
            }

            manager.Update(person);

            if (person.HasPhoto)
                ViewBag.Photo = "/Uploads/Members/" + uid + ".jpg";

            return View(info);
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Person person, string Pass, HttpPostedFileBase img)
        {
            UserStore<Person> store = new UserStore<Person>(UnitOfWork.Create());

            UserManager<Person> manager = new UserManager<Person>(store);

            var result = manager.Create(person, Pass);

            if (result.Succeeded)
            {
                //Uploads/Members/
                //resim varsa kişinin idsi ile kaydet
                //anasayfaya yönlendir

                if (img != null)
                {
                    string path = Server.MapPath("/Uploads/Members/");
                    img.SaveAs(path + person.Id + ".jpg");

                    person.HasPhoto = true;
                    manager.Update(person);
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //View içine hataları gönder
                //Hataları uygun bir html ile göster
                ViewBag.Errors = result.Errors;
            }

            return View();
        }

        public ActionResult _LoginModal()
        {
            return View();
        }

        public JsonResult Login(LoginViewModel info)
        {
            //1. Signin managera ulaş
            ApplicationSignInManager signInManager = HttpContext.GetOwinContext().Get<ApplicationSignInManager>();

            //2. Giriş yapmayı dene (result döner)

            SignInStatus result = signInManager.PasswordSignIn(info.Email, info.Password, true, false);

            //3. Sonucu döndür
            switch (result)
            {
                case SignInStatus.Success:
                    return Json(new { success = true });
                case SignInStatus.Failure:
                    return Json(new { success = false });
            }
            return Json(new { success = false });
        }
    }
}

SozlukMVC/Controllers/WordRequestsController.cs
using BLL;
using Entity;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SozlukMVC.Controllers
{
    public class WordRequestsController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();
        public ActionResult Index(int? sil)
        {
            if (sil.HasValue)
            {
                _uw.WordRequests.Delete(sil.Value);
                _uw.Complete();
            }

            var list = _uw.WordRequests.GetAll();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
          
            //<option>
            ViewBag.Langs = _uw.Languages.GetAll()
                .Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            return View();
        }

        [HttpPost]
        public ActionResult Create(WordRequest r)
        {
            if (ModelState.IsValid)
            {
                string uid = User.Identity.GetUserId();
                var user = _uw.db.Users.Find(uid);
                r.Person = user;
                _uw.WordRequests.Add(r);
                _uw.Complete();
                return RedirectToAction("Index");
            }
            ViewBag.Langs = _uw.Languages.GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            return View(r);
        }
    }
}

SozlukMVC/Controllers/WordsController.cs
using BLL;
using Entity;
using Entity.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace SozlukMVC.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class WordsController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();

        public ActionResult Index(int? langid, int? sil)
        {
            if (sil.HasValue)
            {
                _uw.Words.Delete(sil.Value);
                _uw.Complete();
                return RedirectToAction("Index", new { @langid = langid });
            }

            List<SelectListItem> langs = _uw.Languages.GetAll().Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            langs.Insert(0, new SelectListItem()
            {
                Text = "Seçiniz",
                Value = ""
            });

            ViewData["LangOptions"] = langs;

            if (langid.HasValue)
            {
                ViewBag.langid = langid.Value;
                var list = _uw.Words
                    .Search(x => x.Language_Id == langid.Value);
                return View(list);
            }
            else
                return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            //ViewBag.LangOptions = _uw.Languages.GetAll();
            //ViewData["LangOptions"] = _uw.Languages.GetAll();
            TempData["LangOptions"] = _uw.Languages
                .GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            return View();
        }
        [HttpPost]
        public ActionResult Create(string WordTxt, int LanguageId)
        {
            if (string.IsNullOrEmpty(WordTxt))
                ModelState.AddModelError("", "Kelime boş bırakılamaz");

            if (ModelState.IsValid)
            {
                Word w = new Word();
                w.WordTxt = WordTxt;
                w.Language_Id = LanguageId;
                w.Translations = new List<Word>();
                var langs = _uw.Languages.GetAll();

             
                foreach (var item in langs)
                {
                    string input = Request.Form["ceviri" + item.Id];

                    string[] words = input.Split(',');

                    foreach (string a in words)
                    if (!string.IsNullOrEmpty(a))
                    {
                        Word ceviri = new Word();
                        ceviri.Language_Id = item.Id;
                        ceviri.WordTxt = a;
                        w.Translations.Add(ceviri);
                    }


                }

                _uw.Words.Add(w);
                _uw.Complete();
                return RedirectToAction("Index");
            }


            return View();
        }

        public JsonResult AutoComplete(int langid, string q)
        {
            var c = Thread.CurrentThread.CurrentCulture;
            var list = _uw.Words
                 .Search(x => x.Language_Id == langid && x.WordTxt.ToLower().StartsWith(q.ToLower()))
                 .Select(x => x.WordTxt)
                 .ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

SozlukMVC/Views/Shared/_Layout.cshtml
<!Doctype html>
<html>
<head>
    <title>Sözlük</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a class="navbar-brand" href="#">Login dropdown</a>*@
                @Html.ActionLink("Sözlük", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @*<a href="/Home/About>Hakkımızda</a>"*@
                    <li class="active">
                        @Html.ActionLink("Hakkımızda", "About", "Home")
                    </li>
                    @*<a href="/Home/Contact>İletişim</a>"*@
                    <li>
                        @Html.ActionLink("İletişim", "Contact", "Home")
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Bana Özel <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
   <li>@Html.ActionLink("Hesabım","MyAccount","Members")</li>
   <li>@Html.ActionLink("Şifremi Değiştir","ChangePass","Members")</li>
   <li class="divider"></li>
   <li>@Html.ActionLink("Kelime İstekleri","Index","WordRequests")</li>

@if (User.IsInRole("Admin"))
{
    <li class="divider"></li>
    <li>@Html.ActionLink("Kelimeler", "Index", "Words")</li>
    <li>@Html.ActionLink("Yeni Kelime Ekle","Create","Words")</li>
}

                            </ul>
                        </li>
                    }
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <p class="navbar-text">Merhaba @User.Identity.Name</p>
                        </li>
                        <li>
                            @*<a href="/Members/LogOff>Çıkış Yap</a>"*@
                            @Html.ActionLink("Çıkış Yap", "LogOff", "Members")
                        </li>
                    }
                    else
                    {
                        <li>
                            <p class="navbar-text">Already have an account?</p>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
                            <ul id="login-dp" class="dropdown-menu">
                                <li>
                                    <div class="row">
                                        <div class="col-md-12">
                                            Login via
                                            <div class="social-buttons">
                                                <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                                                <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                                            </div>
                                            or
                                            @Html.Action("_LoginModal", "Members")
                                        </div>
                                        <div class="bottom text-center">
                                            New here ?
                                            @*<a href="#"><b>Join Us</b></a>*@
                                            @Html.ActionLink("Kayıt Ol", "Register", "Members", null, new { @class = "bold" })
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    @RenderBody()

    @RenderSection("Scripts",false)
</body>
</html>